"""
Markdown Report Generator for RepoForge.
Creates a detailed, human-readable markdown report for PRs, READMEs, or documentation.
"""

from typing import Dict, Any, List
from datetime import datetime


class MarkdownReport:
    """
    Generates a comprehensive markdown report from the scan data.
    Suitable for attaching to pull requests or storing in docs/.
    """

    def __init__(self, report_data: Dict[str, Any]):
        """
        Args:
            report_data: The full aggregated report dict.
                         Expected keys: generated_at, total_repos, healthy, stale,
                         critical, repos (list of repo statuses).
        """
        self.data = report_data
        self.repos = report_data.get("repos", [])
        self.total = report_data.get("total_repos", len(self.repos))
        self.healthy = report_data.get("healthy", 0)
        self.stale = report_data.get("stale", 0)
        self.critical = report_data.get("critical", 0)
        self.generated = report_data.get("generated_at", datetime.now().isoformat())

    def generate(self) -> str:
        """Returns the full markdown report."""
        lines = []

        # Header
        lines.append("# 📊 RepoForge Health Report")
        lines.append("")
        lines.append(f"**Generated:** `{self.generated}`")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Summary Table
        lines.append("## 📈 Overall Summary")
        lines.append("")
        lines.append("| Status | Count | Percentage |")
        lines.append("|--------|-------|------------|")
        lines.append(f"| 🟢 Healthy | {self.healthy} | {self._pct(self.healthy)} |")
        lines.append(f"| 🟡 Stale / Warning | {self.stale} | {self._pct(self.stale)} |")
        lines.append(f"| 🔴 Critical | {self.critical} | {self._pct(self.critical)} |")
        lines.append(f"| **Total** | **{self.total}** | **100%** |")
        lines.append("")

        # Detailed repo table
        lines.append("## 📋 Repository Details")
        lines.append("")
        lines.append("| Repo | Branch | Health Score | Status | Last Commit |")
        lines.append("|------|--------|--------------|--------|-------------|")

        for r in self.repos:
            name = r.get("name", "Unknown")
            branch = r.get("branch", "N/A")
            score = r.get("health_score", 0)
            status = r.get("status_message", "Unknown")
            commit = r.get("last_commit_msg", "N/A")[:30]
            lines.append(f"| {name} | {branch} | {score} | {status} | {commit} |")

        lines.append("")

        # Critical section
        critical_repos = [r for r in self.repos if r.get("health_score", 100) < 50]
        if critical_repos:
            lines.append("## 🚨 Critical Repositories (Urgent)")
            lines.append("")
            for r in critical_repos:
                lines.append(f"- **{r.get('name')}** (Score: {r.get('health_score')})")
                lines.append(f"  - Status: {r.get('status_message')}")
                lines.append(f"  - Branch: {r.get('branch', 'N/A')}")
                if r.get("error"):
                    lines.append(f"  - Error: `{r.get('error')}`")
                lines.append("")

        # Language / Metadata enrichment (if present)
        # Check if first repo has language stats to show aggregate
        first_repo = self.repos[0] if self.repos else {}
        if "languages" in first_repo:
            lines.append("## 🧠 Language Distribution (First repo sample)")
            lines.append("")
            lines.append("| Language | Files | Lines |")
            lines.append("|----------|-------|-------|")
            lang_data = first_repo.get("languages", {})
            for lang, stats in lang_data.items():
                lines.append(f"| {lang} | {stats.get('files', 0)} | {stats.get('lines', 0):,} |")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append(f"_Report generated by RepoForge Engine at {self.generated}_")
        lines.append("")

        return "\n".join(lines)

    def _pct(self, value: int) -> str:
        """Calculate percentage safely."""
        if self.total == 0:
            return "0.0%"
        return f"{(value / self.total) * 100:.1f}%"

    def save(self, filepath: str) -> None:
        """Utility to write the report directly to a file."""
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(self.generate())